/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
load config files on ubuntu or from regu: configs/001_localimplicitsr_swinir_div2k_g1_c64b16_1000k_unfold_lec_mulwkv_res_nonlocal.py
Traceback (most recent call last):
  File "/mnt/diskb/penglong/war/CiaoSR-test/tools/test.py", line 162, in <module>
    main()
  File "/mnt/diskb/penglong/war/CiaoSR-test/tools/test.py", line 72, in main
    cfg = mmcv.Config.fromfile(args.config)
  File "/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/site-packages/mmcv/utils/config.py", line 342, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/site-packages/mmcv/utils/config.py", line 210, in _file2dict
    mod = import_module(temp_module_name)
  File "/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/tmpdmhwt7h8/tmpp_ixrpiz.py", line 63, in <module>
TypeError: '<=' not supported between instances of 'str' and 'int'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f616e97d820>
Traceback (most recent call last):
  File "/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/tempfile.py", line 461, in __del__
    self.close()
  File "/mnt/diskb/penglong/anaconda3/envs/xpz_mamba2/lib/python3.9/tempfile.py", line 457, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpdmhwt7h8/tmpp_ixrpiz.py'
